### ISSUE TITLE
Template seems to be broken when selecting another language.

### ISSUE THREAD

**Issue by matthiaz** [Vardot/platformsh-varbase9#21]
### Describe the bug

Creating a new varbase project fails during installation when selecting Francais

### Include some logs

An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?profile=varbase&langcode=fr&id=3&op=do_nojs&op=do
StatusText: OK
ResponseText: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "path_alias.manager". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 1030 of /app/vendor/symfony/dependency-injection/ContainerBuilder.php)

### Reproducing

To reproduce

- Create a new project
- Select template varbase
- Select the language `Francais`
- error pops up `Drupal est deja installe`
- Retry second time: works, but a later step crashes with
```
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?profile=varbase&langcode=fr&id=3&op=do_nojs&op=do
StatusText: OK
ResponseText: Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "path_alias.manager". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 1030 of /app/vendor/symfony/dependency-injection/ContainerBuilder.php).```

### Expected behavior

A working varbase environment

### Your environment

NA

### Screenshots

_No response_

### Additional context

_No response_

**Comment by Natshah** [comment]
Issue [#3277590](https://www.drupal.org/i/3277590) by [Abdullah Yassin](https://www.drupal.org/u/abdullah-yassin): Have a Varbase installation requirement ( notification, not a blocker)
Changed
[Requirements](https://docs.varbase.vardot.com/developers/installing-varbase/requirements)
PHP 7.4 or higher. PHP 8.0 is recommended.

Changed
[Varbase Project Template for Platform.sh](https://github.com/vardot/platformsh-varbase#services)
[The runtime the application uses](https://github.com/Vardot/platformsh-varbase/blob/master/.platform.app.yaml#L10)
 type: 'php:8.0'

Changed
[Varbase Project Template for Lando](https://github.com/vardot/platformsh-varbase#services)
[Lando PHP config](https://github.com/Vardot/platformsh-varbase/blob/master/.platform.app.yaml#L10)
php: '8.0'
