### ISSUE TITLE
Change bin-dir from Trash to bin folder

### ISSUE THREAD

**Issue by ahmad-abbad** [Vardot/platformsh-varbase9#28]
### Describe the bug

bin-dir must be bin not trash
"bin-dir": "~/.Trash" => "bin-dir": "bin/",

### Include some logs

drush errors

### Reproducing

1- install varbase template on PSH server
2- check the composer.json
3- check bin-dir

### Expected behavior

bin-dir to be bin

### Your environment

PSH

**Comment by Natshah** [comment]
Committed ... Thank you

**Comment by Natshah** [comment]
Change bin-dir: bin/ to ~/.Trash in the composer.json file #26 
Only when the host has multiple apps in the same directory

Example: 
- varbase_portal
- varbase_api
- varbase_ai
- app_react
- app_docs
