### ISSUE TITLE
Add node version for .lando file

### ISSUE THREAD

**Issue by ahmad-abbad** [Vardot/platformsh-varbase9#29]
### Describe the bug

node version must be => 16 
`  node:
    type: node:16`

### Include some logs

The engine "node" is incompatible with this module. Expected version 16

### Reproducing

1- lando start 
The engine "node" is incompatible with this module. Expected version

### Expected behavior

add version for node

### Your environment

PSH

**Comment by Natshah** [comment]
Committed ... Thank you
