### ISSUE TITLE
Fix Drupal 9.4 compatibility with Hal module not in core anymore

### ISSUE THREAD

**Issue by QusaiTaha12** [Vardot/platformsh-varbase9#30]
### Describe the bug

There are fatal errors after the drupal 9.4 update + https://www.drupal.org/project/hal module usage
+ wrong dependency declaration.

[Issue #3294780: Drupal 9.4 compatibility with Hal module not in core anymore](https://www.drupal.org/project/better_normalizers/issues/3294780)

### Include some logs

```
  Problem 1
    - drupal/better_normalizers[1.0.0-beta1, ..., 1.0.0-beta2] require drupal/core ~8.0 -> found drupal/core[8.0.0-beta6, ..., 8.9.x-dev] but it conflicts with your root composer.json require (^9.5).
    - drupal/better_normalizers[1.0.0-beta3, ..., 1.x-dev] require drupal/hal ^8.3 -> found drupal/hal[dev-1.x, dev-1.0.x, dev-2.x, 1.0.0, ..., 1.x-dev (alias of dev-1.x), 2.0.0, 2.0.1, 2.x-dev (alias of dev-2.x)] but it does not match the 
constraint.
    - Root composer.json requires drupal/better_normalizers 1.* -> satisfiable by drupal/better_normalizers[1.0.0-beta1, ..., 1.x-dev].
```

### Reproducing

Composer update

### Expected behavior

Composer update working well

Add    
```
 "replace": {
        "drupal/hal": "*"
     },
```
     
     to composer.json

### Your environment

Locally

**Comment by Natshah** [comment]
**Default Content 2.0.0-alpha2**
https://www.drupal.org/project/default_content/releases/2.0.0-alpha2

> **IMPORTANT:** To import old hal+json files, the hal module must be explicitly required by the module containing that default content. Alternatively and recommended, re-export the default content on an installed site first. Support for hal will be completely removed in a future version. See https://www.drupal.org/node/3296226 for more information.
